name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      continue: 'false'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check for changes in service path
      run: |
        if git diff --quiet HEAD^ HEAD -- ./services ./Dockerfile; then
          echo "No changes detected. Skipping build and deploy."
          echo "continue=false" >> $GITHUB_ENV
        else
          echo "Changes detected. Proceeding with build and deploy."
          echo "continue=true" >> $GITHUB_ENV
        fi

    - name: Set up Docker Buildx
      if: env.continue == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker
      if: env.continue == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      if: env.continue == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ vars.IMAGE_NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max